//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afriauscare.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public bank()
        {
            this.bank_information = new HashSet<bank_information>();
        }
    
        public int bank_id { get; set; }
        public string bank_name { get; set; }
        public string bank_alias { get; set; }
    
        public virtual ICollection<bank_information> bank_information { get; set; }
    }
}
