//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afriauscare.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_information
    {
        public int bank_information_id { get; set; }
        public int bank_id { get; set; }
        public string abn_number { get; set; }
        public string bsb_number { get; set; }
        public string account_number { get; set; }
        public bool is_default { get; set; }
    
        public virtual bank bank { get; set; }
    }
}
