//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afriauscare.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_information
    {
        public int contact_id { get; set; }
        public string phone_number { get; set; }
        public string mobile_number { get; set; }
        public string fax_number { get; set; }
        public string email_address { get; set; }
        public string contact_address { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> suburb_id { get; set; }
        public string postcode { get; set; }
    }
}
