//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryContent
    {
        public int GalleryContentID { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public string GalleryContentPath { get; set; }
        public Nullable<int> GalleryContentIndex { get; set; }
        public Nullable<bool> GalleryContentIsActive { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
