//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using Afriauscare.DataBaseLayer;
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.GalleryContents = new HashSet<GalleryContent>();
        }
    
        public int GalleryId { get; set; }
        public string GalleryTitle { get; set; }
        public string GalleryDescription { get; set; }
        public Nullable<System.DateTime> GalleryEventDate { get; set; }
    
        public virtual ICollection<GalleryContent> GalleryContents { get; set; }
    }
}
