//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afriauscare.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_user_activity
    {
        public int log_user_id { get; set; }
        public int user_id { get; set; }
        public string module_name { get; set; }
        public string action_executed { get; set; }
        public System.DateTime datetime_action { get; set; }
    
        public virtual User User { get; set; }
    }
}
