//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.suburbs = new HashSet<suburb>();
        }
    
        public int state_id { get; set; }
        public string state_name { get; set; }
        public string state_alias { get; set; }
    
        public virtual ICollection<suburb> suburbs { get; set; }
    }
}
